export const LANGUAGES = [
    { code: "Afrikaans", label: "Afrikaans", voiceCode: "af-ZA" },
    { code: "Albanian", label: "Albanian", voiceCode: "sq-AL" },
    { code: "Amharic", label: "Amharic", voiceCode: "am-ET" },
    { code: "Arabic", label: "Arabic", voiceCode: "ar-SA" },
    { code: "Armenian", label: "Armenian", voiceCode: "hy-AM" },
    { code: "Assamese", label: "Assamese", voiceCode: "as-IN" },
    { code: "Azerbaijani", label: "Azerbaijani", voiceCode: "az-AZ" },
    { code: "Basque", label: "Basque", voiceCode: "eu-ES" },
    { code: "Bengali", label: "Bengali", voiceCode: "bn-IN" },
    { code: "Bosnian", label: "Bosnian", voiceCode: "bs-BA" },
    { code: "Bulgarian", label: "Bulgarian", voiceCode: "bg-BG" },
    { code: "Burmese", label: "Burmese", voiceCode: "my-MM" },
    { code: "Catalan", label: "Catalan", voiceCode: "ca-ES" },
    { code: "Central Kurdish", label: "Central Kurdish", voiceCode: "ckb-IQ" },
    { code: "Chinese", label: "Chinese", voiceCode: "zh-CN" },
    { code: "Croatian", label: "Croatian", voiceCode: "hr-HR" },
    { code: "Czech", label: "Czech", voiceCode: "cs-CZ" },
    { code: "Danish", label: "Danish", voiceCode: "da-DK" },
    { code: "Dutch", label: "Dutch", voiceCode: "nl-NL" },
    { code: "English", label: "English", voiceCode: "en-US" },
    { code: "Estonian", label: "Estonian", voiceCode: "et-EE" },
    { code: "Finnish", label: "Finnish", voiceCode: "fi-FI" },
    { code: "French", label: "French", voiceCode: "fr-FR" },
    { code: "Galician", label: "Galician", voiceCode: "gl-ES" },
    { code: "Georgian", label: "Georgian", voiceCode: "ka-GE" },
    { code: "German", label: "German", voiceCode: "de-DE" },
    { code: "Greek", label: "Greek", voiceCode: "el-GR" },
    { code: "Gujarati", label: "Gujarati", voiceCode: "gu-IN" },
    { code: "Hausa", label: "Hausa", voiceCode: "ha-NG" },
    { code: "Hebrew", label: "Hebrew", voiceCode: "he-IL" },
    { code: "Hindi", label: "Hindi", voiceCode: "hi-IN" },
    { code: "Hungarian", label: "Hungarian", voiceCode: "hu-HU" },
    { code: "Icelandic", label: "Icelandic", voiceCode: "is-IS" },
    { code: "Indonesian", label: "Indonesian", voiceCode: "id-ID" },
    { code: "Irish", label: "Irish", voiceCode: "ga-IE" },
    { code: "Italian", label: "Italian", voiceCode: "it-IT" },
    { code: "Japanese", label: "Japanese", voiceCode: "ja-JP" },
    { code: "Kannada", label: "Kannada", voiceCode: "kn-IN" },
    { code: "Kazakh", label: "Kazakh", voiceCode: "kk-KZ" },
    { code: "Korean", label: "Korean", voiceCode: "ko-KR" },
    { code: "Latvian", label: "Latvian", voiceCode: "lv-LV" },
    { code: "Lithuanian", label: "Lithuanian", voiceCode: "lt-LT" },
    { code: "Macedonian", label: "Macedonian", voiceCode: "mk-MK" },
    { code: "Malayalam", label: "Malayalam", voiceCode: "ml-IN" },
    { code: "Marathi", label: "Marathi", voiceCode: "mr-IN" },
    { code: "Nepali", label: "Nepali", voiceCode: "ne-NP" },
    { code: "Norwegian", label: "Norwegian", voiceCode: "no-NO" },
    { code: "Oriya", label: "Oriya", voiceCode: "or-IN" },
    { code: "Pashto", label: "Pashto", voiceCode: "ps-AF" },
    { code: "Persian", label: "Persian", voiceCode: "fa-IR" },
    { code: "Polish", label: "Polish", voiceCode: "pl-PL" },
    { code: "Portuguese", label: "Portuguese", voiceCode: "pt-PT" },
    { code: "Romanian", label: "Romanian", voiceCode: "ro-RO" },
    { code: "Russian", label: "Russian", voiceCode: "ru-RU" },
    { code: "Serbian", label: "Serbian", voiceCode: "sr-RS" },
    { code: "Sinhala", label: "Sinhala", voiceCode: "si-LK" },
    { code: "Slovak", label: "Slovak", voiceCode: "sk-SK" },
    { code: "Slovene", label: "Slovene", voiceCode: "sl-SI" },
    { code: "Somali", label: "Somali", voiceCode: "so-SO" },
    { code: "Spanish", label: "Spanish", voiceCode: "es-ES" },
    { code: "Swahili", label: "Swahili", voiceCode: "sw-KE" },
    { code: "Swedish", label: "Swedish", voiceCode: "sv-SE" },
    { code: "Tagalog", label: "Tagalog", voiceCode: "tl-PH" },
    { code: "Tamil", label: "Tamil", voiceCode: "ta-IN" },
    { code: "Telugu", label: "Telugu", voiceCode: "te-IN" },
    { code: "Thai", label: "Thai", voiceCode: "th-TH" },
    { code: "Turkish", label: "Turkish", voiceCode: "tr-TR" },
    { code: "Ukrainian", label: "Ukrainian", voiceCode: "uk-UA" },
    { code: "Urdu", label: "Urdu", voiceCode: "ur-PK" },
    { code: "Vietnamese", label: "Vietnamese", voiceCode: "vi-VN" },
    { code: "Welsh", label: "Welsh", voiceCode: "cy-GB" },
    { code: "Yoruba", label: "Yoruba", voiceCode: "yo-NG" },
    { code: "Zulu", label: "Zulu", voiceCode: "zu-ZA" },
].sort((a, b) => a.label.localeCompare(b.label));

export const REGIONS = [
    { id: "world", name: "Select Region", languageCode: "", flag: "🌍" },
    { id: "us", name: "United States", languageCode: "English", flag: "🇺🇸" },
    { id: "uk", name: "United Kingdom", languageCode: "English", flag: "🇬🇧" },
    { id: "fr", name: "France", languageCode: "French", flag: "🇫🇷" },
    { id: "es", name: "Spain", languageCode: "Spanish", flag: "🇪🇸" },
    { id: "de", name: "Germany", languageCode: "German", flag: "🇩🇪" },
    { id: "it", name: "Italy", languageCode: "Italian", flag: "🇮🇹" },
    { id: "jp", name: "Japan", languageCode: "Japanese", flag: "🇯🇵" },
    { id: "cn", name: "China", languageCode: "Chinese", flag: "🇨🇳" },
    { id: "in", name: "India", languageCode: "Hindi", flag: "🇮🇳" },
    { id: "br", name: "Brazil", languageCode: "Portuguese", flag: "🇧🇷" },
    { id: "ru", name: "Russia", languageCode: "Russian", flag: "🇷🇺" },
    { id: "sa", name: "Saudi Arabia", languageCode: "Arabic", flag: "🇸🇦" },
    { id: "kr", name: "South Korea", languageCode: "Korean", flag: "🇰🇷" },
    { id: "nl", name: "Netherlands", languageCode: "Dutch", flag: "🇳🇱" },
    { id: "se", name: "Sweden", languageCode: "Swedish", flag: "🇸🇪" },
    { id: "tr", name: "Turkey", languageCode: "Turkish", flag: "🇹🇷" },
    { id: "pl", name: "Poland", languageCode: "Polish", flag: "🇵🇱" },
    { id: "id", name: "Indonesia", languageCode: "Indonesian", flag: "🇮🇩" },
    { id: "vn", name: "Vietnam", languageCode: "Vietnamese", flag: "🇻🇳" },
    { id: "th", name: "Thailand", languageCode: "Thai", flag: "🇹🇭" },
    { id: "gr", name: "Greece", languageCode: "Greek", flag: "🇬🇷" },
    { id: "il", name: "Israel", languageCode: "Hebrew", flag: "🇮🇱" },
    { id: "ke", name: "Kenya", languageCode: "Swahili", flag: "🇰🇪" },
    { id: "za", name: "South Africa", languageCode: "Zulu", flag: "🇿🇦" },
];
